---
- name: Update apt cache 
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'
- name: Enable br_netfilter for k8s iptables
  modprobe:
    name: br_netfilter
    state: present
- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none
- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
- name: iptables disable ip forward
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
  loop:
    - net.ipv4.ip_forward
  when: >
    ( ansible_distribution != 'Debian'
    or ansible_distribution_major_version | int < 10 )
    and kubernetes_role != 'master'