---
- name: Setup kubeconfig for vagrant user
  command: "{{ item }}"
  with_items:
    - mkdir -p /home/vagrant/.kube
    - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    - chown vagrant:vagrant /home/vagrant/.kube/config
  changed_when: false
  when: kubernetes_role == 'master'

- name: copy kubeconfig to ansible host
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: ../config/
    flat: yes
    fail_on_missing: yes
  when: kubernetes_role == 'master'